### ISSUE TITLE
Implement Markov chain text generation

### ISSUE THREAD

**Issue by carlthome** [ai14/prosammgen#3]

**Comment by carlthome** [comment]
@johnPertoft Make sure to document decisions in this issue (with scientific references) about how the Markov chain is implemented. Optimal N for the N-grams for example (bias/variance dilemma).

**Comment by carlthome** [comment]
Issue done? Bugs left? Improvements to be made?

**Comment by johnPertoft** [comment]
Sorry for not answering earlier. I think it's done. One improvement could be smoothing of some kind, don't really know how much we would gain from it. Another improvement could be to pass the previous ngram to the markov textgenerator so that it could try to build from that. In most cases I don't think the markov chain would contain that ngram since that ngram would come from our defined grammar and the markov chain is only trained on other resources so it might not be worth it either.

What do you think?

**Comment by carlthome** [comment]
No worries.

Passing ngrams seems unnecessary, agreed.

Smoothing should be attempted, I think, but it deserves its own issue. Feel free to create one.

----- Ursprungligt meddelande -----
Från: "johnPertoft" notifications@github.com
Skickat: ‎2014-‎10-‎22 14:39
Till: "ai14/prosammgen" prosammgen@noreply.github.com
Kopia: "Carl Thomé" carlthome@gmail.com
Ämne: Re: [prosammgen] Implement Markov chain text generation (#3)

Sorry for answering earlier. I think it's done. One improvement could be smoothing of some kind, don't really know how much we would gain from it. Another improvement could be to pass the previous ngram to the markov textgenerator so that it could try to build from that. In most cases I don't think the markov chain would contain that ngram since that ngram would come from our defined grammar and the markov chain is only trained on other resources so it might not be worth it either.
What do you think?

**Comment by carlthome** [comment]
https://github.com/ai14/prosammgen/issues/28
